bbnet: adding initial support for sync

diff --git a/src/bbnet.in b/src/bbnet.in
--- a/src/bbnet.in
+++ b/src/bbnet.in
@@ -52,6 +52,20 @@ NET_ORDER_PRE="builtin global apps cluster local"
 NET_ORDER_POST="builtin global apps cluster local"
 NET_ORDER_UP="builtin global apps cluster local"
 NET_ORDER_DOWN="local cluster apps global builtin"
+NET_ORDER_SYNC="cluster apps global"
+NET_SYNC_PRIORITY="script git rsync"
+NET_SYNC_RESTARTS=yes
+NET_SYNC_TIMEOUT=60
+
+
+NET_SYNC_DID_UPDATE=no
+export NET_SYNC_DID_UPDATE
+
+
+GIT_HTTP_LOW_SPEED_LIMIT=1000
+GIT_HTTP_LOW_SPEED_TIME=5
+export GIT_HTTP_LOW_SPEED_LIMIT
+export GIT_HTTP_LOW_SPEED_TIME
 
 
 ###########
@@ -139,8 +153,12 @@ config_check()
       OPTS="${OPTS} order_down"
       OPTS="${OPTS} order_posthook"
       OPTS="${OPTS} order_prehook"
+      OPTS="${OPTS} order_sync"
       OPTS="${OPTS} order_up"
       OPTS="${OPTS} quiet"
+      OPTS="${OPTS} sync_priority"
+      OPTS="${OPTS} sync_restarts"
+      OPTS="${OPTS} sync_timeout"
       OPTS="${OPTS} verbose"
       for OPT in ${OPTS}; do
          config_option "${OPT}" > /dev/null
@@ -153,6 +171,7 @@ config_check()
       # check boolean options
       OPTS=""
       OPTS="${OPTS} quiet"
+      OPTS="${OPTS} sync_restarts"
       OPTS="${OPTS} verbose"
       for OPT in ${OPTS}; do
          config_option "${OPT}" |egrep -i '^yes$|^no$|^$' > /dev/null
@@ -164,6 +183,7 @@ config_check()
 
       # check numeric options
       OPTS=""
+      OPTS="${OPTS} sync_timeout"
       for OPT in ${OPTS}; do
          config_option "${OPT}" |egrep '^([0-9]{1,5}){0,1}$' > /dev/null
          if test ${?} -ne 0;then
@@ -183,6 +203,7 @@ config_check()
       OPTS="${OPTS} order_down"
       OPTS="${OPTS} order_posthook"
       OPTS="${OPTS} order_prehook"
+      OPTS="${OPTS} order_sync"
       OPTS="${OPTS} order_up"
       for OPT in ${OPTS}; do
          TMP_APPS=0
@@ -226,6 +247,43 @@ config_check()
          fi
          if test ${TMP_NONE} -gt 1;then
             echo "config error: duplicate level 'none' for order in '${OPT}'"
+            CONFIG_OK=no
+         fi
+      done
+
+      # check sync priority options
+      OPTS=""
+      OPTS="${OPTS} sync_priority"
+      for OPT in ${OPTS}; do
+         TMP_GIT=0
+         TMP_NONE=0
+         TMP_RSYNC=0
+         TMP_SCRIPT=0
+         for VAL in $(config_option ${OPT} "git" A-Z a-z); do
+            case "${VAL}" in
+               git)     TMP_GIT=$((${TMP_GIT}+1)) ;;
+               none)    TMP_NONE=$((${TMP_NONE}+1)) ;;
+               rsync)   TMP_RSYNC=$((${TMP_RSYNC}+1)) ;;
+               script)  TMP_SCRIPT=$((${TMP_SCRIPT}+1)) ;;
+               *)       echo "config error: unknown value '${VAL}' for priority in '${OPT}'"
+                        CONFIG_OK=no
+                        ;;
+            esac
+         done
+         if test ${TMP_GIT} -gt 1;then
+            echo "config error: duplicate priority 'git' in '${OPT}'"
+            CONFIG_OK=no
+         fi
+         if test ${TMP_NONE} -gt 1;then
+            echo "config error: duplicate priority 'none' in '${OPT}'"
+            CONFIG_OK=no
+         fi
+         if test ${TMP_RSYNC} -gt 1;then
+            echo "config error: duplicate priority 'rsync' in '${OPT}'"
+            CONFIG_OK=no
+         fi
+         if test ${TMP_SCRIPT} -gt 1;then
+            echo "config error: duplicate priority 'script' in '${OPT}'"
             CONFIG_OK=no
          fi
       done
@@ -528,6 +586,151 @@ do_stop_builtin_list()
 }
 
 
+do_sync()
+{
+   for LEVEL in ${NET_ORDER_SYNC}; do
+      case "${LEVEL}" in
+         apps)    do_sync_dir "${NET_DIR}/apps.d"    "syncing apps root files %s ..." ;
+                  for APP in $( app_list ); do
+                     do_sync_dir "${NET_DIR}/apps.d/${APP}" "syncing app files %s (App: ${APP}) ...";
+                  done;
+                  ;;
+         global)  do_sync_dir "${NET_DIR}/global.d"  "syncing global files %s ..." ;;
+         cluster) do_sync_dir "${NET_DIR}/cluster.d" "syncing cluster files %s ..." ;;
+         builtin) ;;
+         local)   ;;
+         none)    ;;
+         *)       echo "Unknown sync priority \"${PRIORITY}\"" ;;
+      esac
+   done
+
+   export NET_SYNC_DID_UPDATE
+
+   return 0;
+}
+
+
+do_sync_dir()
+{
+   SYNC_DIR="${1}"
+   SYNC_DESC="${2}"
+
+   if test -e "${SYNC_DIR}/.sync_disabled"; then
+      printf "${SYNC_DESC}\n" "disabled";
+      return 0;
+   fi
+
+   for PRIORITY in ${NET_SYNC_PRIORITY}; do
+      case "${PRIORITY}" in
+         git)     do_sync_method_git    && return 0;;
+         rsync)   do_sync_method_rsync  && return 0;;
+         script)  do_sync_method_script && return 0;;
+         *)       echo "unknown: ${SYNC_DESC}"; ;;
+      esac
+   done
+
+   return 0;
+}
+
+
+do_sync_method_git()
+{
+   if test ! -d "${SYNC_DIR}/.git" && test ! -f "${SYNC_DIR}/.git"; then
+      return 1;
+   fi
+
+   printf "${SYNC_DESC}\n" "via git";
+
+   # determine if the timeout util is available
+   TIMEOUT_UTIL="$(which timeout 2> /dev/null)"
+   if test ! -z "${TIMEOUT_UTIL}";then
+      TIMEOUT_UTIL="${TIMEOUT_UTIL} ${NET_SYNC_TIMEOUT}"
+   fi
+
+   # run git
+   (
+      cd ${SYNC_DIR} || return 1;
+
+      URL="$(git remote get-url origin 2>/dev/null)"
+      if test -z "${URL}"; then
+         echo "missing git remote 'origin', not syncing"
+         return 0;
+      fi
+
+      BRANCH="$(git branch |grep '^* ' |awk '{print$2}')"
+      if test -z "${BRANCH}"; then
+         echo "unable to determine git branch, not syncing"
+         return 0;
+      fi
+
+      # fetch remote updates and check for differences
+      ${TIMEOUT_UTIL} git fetch origin || return 0;
+      git diff \
+         --exit-code \
+         origin/${BRANCH} \
+         > /dev/null \
+         2> /dev/null \
+         || NET_SYNC_DID_UPDATE=yes;
+
+      # merge changes
+      git checkout .                                  || return 0;
+      git merge origin/${BRANCH}                      || return 0;
+      git submodule update --init --recursive --merge || return 0;
+   )
+
+   return 0;
+}
+
+
+do_sync_method_rsync()
+{
+   if test ! -r "${SYNC_DIR}/.rsync"; then
+      return 1;
+   fi
+
+   printf "${SYNC_DESC}\n" "via rsync";
+
+   # determine if the timeout util is available
+   TIMEOUT_UTIL="$(which timeout 2> /dev/null)"
+   if test ! -z "${TIMEOUT_UTIL}";then
+      TIMEOUT_UTIL="${TIMEOUT_UTIL} ${NET_SYNC_TIMEOUT}"
+   fi
+
+   RSYNC_URL="$(cat "${SYNC_DIR}/.rsync")"
+   if test -z "${RSYNC_URL}"; then
+      echo "the .rsync file is empty, not syncing"
+      return 0;
+   fi
+
+   # run rsync
+   RSYNC_ARGS="${TIMEOUT_UTIL} rsync -aim --delete --exclude=.rsync"
+   RSYNC_OUTPUT="$(${RSYNC_ARGS} $(RSYNC_URL) ${SYNC_DIR})"
+   if test ! -z "${RSYNC_OUTPUT}"; then
+      NET_SYNC_DID_UPDATE=yes;
+   fi;
+
+   return 0;
+}
+
+
+do_sync_method_script()
+{
+   if test ! -x "${SYNC_DIR}/sync"; then
+      return 1
+   fi
+
+   printf "${SYNC_DESC}\n" "via script";
+   ${SYNC_DIR}/sync
+   case $? in
+      0) return 0;;
+      1) return 1;;
+      2) return 2; NET_SYNC_DID_UPDATE=yes;;
+      *) return 1;;
+   esac
+   return 0;
+}
+
+
 do_version()
 {
    echo "Bindle Binaries Linux Networking ${PACKAGE_VERSION} (bbfw)"
@@ -651,6 +854,10 @@ target_showconfig()
    echo "   order_posthook    ${NET_ORDER_POST}"
    echo "   order_up          ${NET_ORDER_UP}"
    echo "   order_down        ${NET_ORDER_DOWN}"
+   echo "   order_sync        ${NET_ORDER_SYNC}"
+   echo "   sync_priority     ${NET_SYNC_PRIORITY}"
+   echo "   sync_restarts     ${NET_SYNC_RESTARTS}"
+   echo "   sync_timeout      ${NET_SYNC_TIMEOUT}"
    echo ""
    config_check > /dev/null 2> /dev/null
    if test $? -ne 0; then
@@ -707,6 +914,45 @@ target_stop()
 }
 
 
+# Function to synchronize config files
+target_sync()
+{
+   # show version
+   do_version
+
+   # minimal config check
+   config_verify || return 1;
+
+   # run pre-hooks
+   do_hook sync pre-hook "${NET_ORDER_PRE}" || return 1;
+
+   # sync files
+   do_sync || return 1;
+
+   # run post-hooks
+   do_hook sync post-hook "${NET_ORDER_POST}" || return 1;
+
+   # determines if network should restart
+   if test "${NET_SYNC_RESTARTS}" != "yes"; then
+      return 0;
+   fi
+   if test "${NET_SYNC_DID_UPDATE}" != "yes"; then
+      return 0;
+   fi
+
+   # run pre-hooks
+   do_hook restart pre-hook "${NET_ORDER_PRE}" || return 1;
+
+   # run network
+   do_restart || return 1;
+
+   # run post-hooks
+   do_hook restart post-hook "${NET_ORDER_POST}" || return 1;
+
+   return 0
+}
+
+
 target_usage()
 {
    echo "Usage: ${PROGRAM_NAME} [ start | stop | restart | show | showconfig | checkconfig ]"
@@ -736,6 +982,10 @@ NET_ORDER_PRE="$(      config_option order_prehook     "${NET_ORDER_PRE}"       
 NET_ORDER_POST="$(     config_option order_posthook    "${NET_ORDER_POST}"      A-Z a-z )"
 NET_ORDER_UP="$(       config_option order_up          "${NET_ORDER_UP}"        A-Z a-z )"
 NET_ORDER_DOWN="$(     config_option order_down        "${NET_ORDER_DOWN}"      A-Z a-z )"
+NET_ORDER_SYNC="$(     config_option order_sync        "${NET_ORDER_SYNC}"      A-Z a-z )"
+NET_SYNC_PRIORITY="$(  config_option sync_priority     "${NET_SYNC_PRIORITY}"   A-Z a-z )"
+NET_SYNC_RESTARTS="$(  config_option sync_restarts     "${NET_SYNC_RESTARTS}"   A-Z a-z )"
+NET_SYNC_TIMEOUT="$(   config_option sync_timeout      "${NET_SYNC_TIMEOUT}"    A-Z a-z )"
 
 
 case "$1" in
@@ -746,6 +996,7 @@ case "$1" in
    'stop')        target_stop          2>&1 | $LOGGER ;;
    'show')        target_show          ;;
    'showconfig')  target_showconfig    || exit 1 ;;
+   'sync')        target_sync          2>&1  | $LOGGER ;;
    'restart')     target_restart       2>&1  | $LOGGER ;;
 
    *) # The default is to bring up all configured interfaces:
